import 'dotenv/config'
import pool from "../database/pool.js"

const memes = [

    { name: "Drake approving", description: "Drake looking away and rejecting one thing, then turning and pointing approvingly at another. Used for preferring one option over another, comparing two things where one is clearly better, upgrade situations, funny trade-offs.", image_url: "https://i.imgflip.com/2/30b1gx.jpg", tags: ["choice", "comparison", "preference"] },
    { name: "Distracted boyfriend", description: "A man walking with his girlfriend turns to stare at another woman passing by. Used for being tempted by something new while ignoring what you already have, chasing shiny things, betraying loyalty.", image_url: "https://i.imgflip.com/2/1ur9b0.jpg", tags: ["temptation", "distraction", "betrayal"] },
    { name: "This is fine dog", description: "A dog sitting calmly in a room that is on fire, sipping coffee and saying everything is fine. Used for ignoring obvious problems, pretending a crisis is normal, coping by denial.", image_url: "https://i.imgflip.com/2/wxica.jpg", tags: ["denial", "crisis", "calm", "disaster"] },
    { name: "Two buttons sweating", description: "A person sweating nervously while trying to decide between two buttons to press. Used for difficult decisions, being forced to choose between two equally bad or good options.", image_url: "https://i.imgflip.com/2/3vy44l.jpg", tags: ["decision", "anxiety", "choice", "dilemma"] },
    { name: "Gru's plan", description: "Gru from Despicable Me presenting a 4-panel plan where the last step unexpectedly repeats or contradicts the first steps. Used for plans that backfire, unintended consequences, realising your own logic is flawed.", image_url: "https://i.imgflip.com/2/26jxvz.jpg", tags: ["plan", "backfire", "logic", "fail"] },
    { name: "Surprised Pikachu", description: "Pikachu with a shocked open-mouth expression. Used when someone is surprised by an obvious and predictable consequence of their own actions.", image_url: "https://i.imgflip.com/2/2kbn1e.jpg", tags: ["surprise", "obvious", "consequence", "shocked"] },
    { name: "Change my mind", description: "Steven Crowder sitting at a table with a sign that says 'Change My Mind'. Used for stating a controversial or bold opinion confidently and daring others to argue.", image_url: "https://i.imgflip.com/24y43o.jpg", tags: ["opinion", "debate", "bold", "controversial"] },
    { name: "One does not simply", description: "Boromir from Lord of the Rings saying 'One does not simply walk into Mordor'. Used for explaining that something is much harder or more complicated than it sounds.", image_url: "https://i.imgflip.com/2/1bij.jpg", tags: ["difficult", "impossible", "warning", "complexity"] },
    { name: "Galaxy brain", description: "A series of expanding glowing brain images representing increasingly wild or absurd logic leaps. Used for overthinking, galaxy-brained reasoning, arriving at a stupid conclusion through complex steps.", image_url: "https://i.imgflip.com/2/2n589r.jpg", tags: ["overthinking", "logic", "absurd", "reasoning"] },
    { name: "Waiting skeleton", description: "A skeleton sitting and waiting for an extremely long time. Used for waiting forever, things that take too long, patience running out, eternal waiting.", image_url: "https://i.imgflip.com/2/2fm6x.jpg", tags: ["waiting", "patience", "forever", "delay"] },
    { name: "Hide the pain Harold", description: "An older man smiling painfully while clearly hiding sadness or discomfort underneath. Used for masking emotions, pretending to be okay, hiding inner suffering with a smile.", image_url: "https://i.imgflip.com/2/gk5el.jpg", tags: ["pain", "hiding", "fake smile", "sadness"] },
    { name: "Woman yelling at cat", description: "A woman pointing and yelling aggressively at a confused white cat sitting at a dinner table. Used for arguments, overreaction, being blamed unfairly, two sides of a conflict.", image_url: "https://i.imgflip.com/2/345v97.jpg", tags: ["argument", "conflict", "yelling", "confusion"] },
    { name: "Is this a pigeon", description: "An anime character mistakenly pointing at a butterfly and calling it a pigeon. Used for misidentifying something, completely wrong assumptions, confidently calling something the wrong thing.", image_url: "https://i.imgflip.com/2/1o00in.jpg", tags: ["misidentification", "wrong", "confusion", "assumption"] },
    { name: "Ight imma head out", description: "SpongeBob slowly getting up from a chair and leaving. Used for quietly exiting an uncomfortable situation, noping out, leaving when things get awkward or bad.", image_url: "https://i.imgflip.com/2/392xtu.jpg", tags: ["leaving", "exit", "awkward", "escape"] },
    { name: "Expanding brain", description: "A series of brain images getting larger and more illuminated with each panel. Used for escalating levels of enlightenment or absurdity, ironic intelligence, biggest brain takes.", image_url: "https://i.imgflip.com/2/1jwhww.jpg", tags: ["intelligence", "escalation", "irony", "big brain"] },
    { name: "Shut up and take my money", description: "Fry from Futurama holding out money eagerly. Used for wanting to buy something immediately, being so impressed you throw money at it.", image_url: "https://i.imgflip.com/60ck.jpg", tags: ["money", "buying", "impressed", "want"] },
    { name: "Batman slapping Robin", description: "Batman slapping Robin mid-sentence to stop him from saying something. Used for shutting down bad takes, interrupting dumb ideas, correcting someone forcefully.", image_url: "https://i.imgflip.com/2/9ehk.jpg", tags: ["interruption", "correction", "slap", "stop"] },
    { name: "Tuxedo Winnie the Pooh", description: "Two panels of Winnie the Pooh — normal and then dressed in a tuxedo looking fancy. Used for the same thing described in a basic way vs a sophisticated pretentious way.", image_url: "https://i.imgflip.com/2/2ybua0.jpg", tags: ["fancy", "pretentious", "upgrade", "sophisticated"] },
    { name: "They're the same picture", description: "Pam from The Office holding up two pictures and saying they're the same. Used for pointing out two things that are identical despite being presented as different.", image_url: "https://i.imgflip.com/2/2za3u1.jpg", tags: ["same", "identical", "comparison", "irony"] },
    { name: "Patrick not their glasses", description: "Patrick Star from SpongeBob wearing a fake nose and glasses as a disguise. Used for terrible disguises, obvious lies, pretending to be something you're clearly not.", image_url: "https://i.imgflip.com/5c7lwq.jpg", tags: ["disguise", "obvious", "hiding", "lie"] },
    { name: "Always has been", description: "Two astronauts in space — one realising something was always true and the other pointing a gun. Used for dark realisations, things that were obvious all along, conspiracy reveals.", image_url: "https://i.imgflip.com/2/46e43q.jpg", tags: ["realisation", "always", "dark", "revelation"] },
    { name: "Megamind no bitches", description: "Megamind presenting with the caption 'No bitches?'. Used for calling someone out for having no friends, luck, or success.", image_url: "https://i.imgflip.com/4acd9e.jpg", tags: ["callout", "failure", "no luck", "roast"] },
    { name: "Stonks", description: "A stick figure in a suit standing in front of an upward graph. Used ironically for bad financial decisions that somehow feel like wins, or genuinely for gains.", image_url: "https://i.imgflip.com/3m13ew.jpg", tags: ["money", "stocks", "irony", "finance", "gains"] },
    { name: "Not stonks", description: "The same stonks meme but with a downward graph. Used for financial losses, bad decisions, things going terribly wrong.", image_url: "https://i.imgflip.com/3m13ew.jpg", tags: ["loss", "failure", "money", "bad decision"] },
    { name: "UNO reverse card", description: "The UNO reverse card being played. Used for turning something back on the person who said it, instant karma, returning energy.", image_url: "https://i.imgflip.com/2/2fye4e.jpg", tags: ["reverse", "karma", "comeback", "turnaround"] },
    { name: "I am the danger", description: "Walter White from Breaking Bad saying 'I am the danger'. Used for asserting dominance, claiming you are the real threat, power moves.", image_url: "https://i.imgflip.com/2/rgttq.jpg", tags: ["power", "dominance", "threat", "breaking bad"] },
    { name: "Panik kalm panik", description: "Three panels showing panic, then calm after a solution, then panic again when a new problem is discovered. Used for false relief, problems getting worse after seemingly resolving.", image_url: "https://i.imgflip.com/2/3qqcim.jpg", tags: ["panic", "calm", "anxiety", "rollercoaster"] },
    { name: "Nobody absolutely nobody", description: "Text meme format saying 'Nobody: / Absolutely nobody: / [person doing something unprompted]'. Used for calling out people who do something random without being asked.", image_url: "https://i.imgflip.com/2/32a7kf.jpg", tags: ["unprompted", "random", "nobody asked", "callout"] },
    { name: "Me and the boys", description: "A group doing something together at a specific time. Used for squad activities, group plans, brotherhood moments.", image_url: "https://i.imgflip.com/2/320xfw.jpg", tags: ["squad", "group", "friends", "together"] },
    { name: "Coffin dance", description: "Pallbearers dancing with a coffin. Used for things that lead to death, metaphorical endings, 'this will kill you' situations.", image_url: "https://i.imgflip.com/4fhsge.jpg", tags: ["death", "ending", "dancing", "funeral"] },
    { name: "Among us sus", description: "Among Us crewmate looking suspicious. Used for calling someone out as suspicious, betrayal, being the imposter.", image_url: "https://i.imgflip.com/4acd9e.jpg", tags: ["sus", "suspicious", "betrayal", "imposter"] },
    { name: "Math lady", description: "A woman with math equations floating around her head. Used for trying to figure something confusing out, doing mental gymnastics, complex calculations.", image_url: "https://i.imgflip.com/1wjvgi.jpg", tags: ["math", "confusion", "thinking", "calculations"] },
    { name: "Doge", description: "A Shiba Inu dog with colourful comic sans text around it expressing internal thoughts. Used for innocent enthusiasm, silly internal monologue, such wow moments.", image_url: "https://i.imgflip.com/2/43a45p.jpg", tags: ["dog", "wow", "enthusiasm", "silly"] },
    { name: "Much wow doge", description: "Doge meme expressing amazement. Used for being genuinely or sarcastically impressed by something.", image_url: "https://i.imgflip.com/2/5hq1fx.jpg", tags: ["amazement", "impressed", "wow", "sarcasm"] },
    { name: "It's free real estate", description: "A man gesturing to an empty field saying it's free real estate. Used for taking advantage of an obvious opportunity, easy wins, claiming unclaimed things.", image_url: "https://i.imgflip.com/2/24r48o.jpg", tags: ["opportunity", "free", "easy", "claiming"] },
    { name: "Task failed successfully", description: "Xbox achievement saying 'Task Failed Successfully'. Used for accidentally achieving something through failure, winning by losing.", image_url: "https://i.imgflip.com/2hgfw.jpg", tags: ["fail", "success", "accidental", "achievement"] },
    { name: "Crying cat", description: "A sad crying cat at a table. Used for feeling sad, emotional pain, being left out or hurt.", image_url: "https://i.imgflip.com/3pnhge.jpg", tags: ["sad", "crying", "emotional", "pain"] },
    { name: "Laughing crying emoji", description: "The 😂 emoji reaction. Used for finding something extremely funny, laughing uncontrollably.", image_url: "https://i.imgflip.com/1g8my4.jpg", tags: ["funny", "laughing", "reaction", "humor"] },
    { name: "Blinking white guy", description: "Drew Scanlon blinking with a blank confused stare. Used for disbelief, processing something absurd, stunned silence.", image_url: "https://i.imgflip.com/36sq.gif", tags: ["disbelief", "confused", "stunned", "processing"] },
    { name: "Roll safe", description: "A man pointing to his temple with a knowing smile. Used for technically correct but flawed logic, avoiding problems through avoidance rather than solving them.", image_url: "https://i.imgflip.com/2/1h7in3.jpg", tags: ["smart", "loophole", "logic", "clever"] },
    { name: "First time", description: "A cowboy looking at something chaotic and asking 'first time?'. Used for welcoming newcomers to a bad situation you've already accepted.", image_url: "https://i.imgflip.com/2/2p3dw0.jpg", tags: ["first time", "veteran", "chaos", "welcome"] },
    { name: "You vs the guy she told you not to worry about", description: "Two contrasting images where the second is clearly superior. Used for unfair comparisons, feeling inadequate next to competition.", image_url: "https://i.imgflip.com/2/1tvu5z.jpg", tags: ["comparison", "jealousy", "inferior", "competition"] },
    { name: "Anakin Padme 4 panel", description: "Anakin and Padme where Padme assumes something positive and Anakin stays silent ominously. Used for dark implications, confirming fears, silent agreement with something bad.", image_url: "https://i.imgflip.com/5c7lwq.jpg", tags: ["dark", "ominous", "silence", "implication"] },
    { name: "Bike fall", description: "A person riding a bike who sticks a stick into their own wheel and falls. Used for self-sabotage, causing your own problems, shooting yourself in the foot.", image_url: "https://i.imgflip.com/2/1b42wl.jpg", tags: ["self-sabotage", "own goal", "stupid", "fall"] },
    { name: "Finally inner peace", description: "A person achieving inner peace right before something chaotic happens. Used for brief moments of calm before disaster, false sense of security.", image_url: "https://i.imgflip.com/2/3nkh17.jpg", tags: ["peace", "calm", "before disaster", "brief"] },
    { name: "Monkey puppet look away", description: "A small monkey puppet turning away awkwardly to avoid acknowledging something. Used for avoiding uncomfortable truths, pretending not to notice something embarrassing.", image_url: "https://i.imgflip.com/2/2gnnjh.jpg", tags: ["avoidance", "awkward", "ignore", "embarrassed"] },
    { name: "Drake no yes", description: "Drake rejecting one option and approving another. Alternate version used for clearer A vs B comparisons.", image_url: "https://i.imgflip.com/2/30b1gx.jpg", tags: ["choice", "yes no", "comparison", "prefer"] },
    { name: "Grandma finds internet", description: "An elderly woman confused by technology. Used for people who are behind the times, technologically lost, out of touch reactions.", image_url: "https://i.imgflip.com/2/1bhw.jpg", tags: ["confused", "technology", "old", "out of touch"] },
    { name: "Running away balloon", description: "A child letting go of a balloon labelled as something important. Used for letting something valuable slip away carelessly.", image_url: "https://i.imgflip.com/on78t.jpg", tags: ["letting go", "careless", "loss", "balloon"] },
    { name: "Disaster girl", description: "A little girl smiling in front of a burning house. Used for secretly causing chaos while looking innocent, enjoying destruction.", image_url: "https://i.imgflip.com/2/23ls.jpg", tags: ["chaos", "destruction", "innocent", "evil"] },
    { name: "Baburao tension", description: "Baburao from Hera Pheri looking extremely stressed and tensed. Used for financial stress, life problems, being in deep trouble, tension situations. Famous Indian meme.", image_url: "https://i.imgflip.com/7y2gzz.jpg", tags: ["tension", "stress", "india", "hera pheri", "money"] },
    { name: "Raju Hera Pheri", description: "Raju from Hera Pheri with a scheming or shocked expression. Used for get rich quick schemes, financial plans going wrong, Indian comedy situations.", image_url: "https://i.imgflip.com/2/5zy4t2.jpg", tags: ["scheme", "money", "india", "hera pheri", "funny"] },
    { name: "Shikhar Dhawan wink", description: "Indian cricketer Shikhar Dhawan giving a confident wink. Used for being confident, flirting, when a plan works out perfectly, swagger moments.", image_url: "https://i.imgflip.com/7y2h00.jpg", tags: ["confident", "wink", "cricket", "india", "swagger"] },
    { name: "Virat Kohli celebration", description: "Virat Kohli celebrating aggressively after scoring or winning. Used for winning moments, proving haters wrong, intense celebration, coming back stronger.", image_url: "https://i.imgflip.com/7y2h00.jpg", tags: ["celebration", "cricket", "india", "winning", "intense"] },
    { name: "MS Dhoni calm", description: "MS Dhoni looking completely calm under pressure. Used for staying cool in stressful situations, pressure doesn't affect me, unshakeable calm.", image_url: "https://i.imgflip.com/7y2h00.jpg", tags: ["calm", "pressure", "cricket", "india", "cool"] },
    { name: "Amitabh Bachchan KBC", description: "Amitabh Bachchan on Kaun Banega Crorepati looking intrigued or questioning. Used for asking obvious questions dramatically, are you sure about that, questioning someone's answer.", image_url: "https://i.imgflip.com/2/4kf38f.jpg", tags: ["question", "india", "kbc", "dramatic", "bollywood"] },
    { name: "Allu Arjun pushpa", description: "Allu Arjun as Pushpa Raj with the iconic style pose and expression. Used for swagger, not bowing down to anyone, South Indian style confidence, flower reference.", image_url: "https://i.imgflip.com/2/63a6xx.jpg", tags: ["swagger", "pushpa", "south india", "confidence", "tollywood"] },
    { name: "Ranveer Singh reaction", description: "Ranveer Singh with an extremely enthusiastic and wild expression. Used for overreacting to good news, being extremely hyped, uncontrollable excitement.", image_url: "https://i.imgflip.com/7y2gzz.jpg", tags: ["excited", "hype", "bollywood", "india", "reaction"] },
    { name: "Indian guy math", description: "Indian guy surrounded by math equations confidently calculating. Used for quick mental math, overcomplicating simple things, being a math genius.", image_url: "https://i.imgflip.com/1wjvgi.jpg", tags: ["math", "india", "calculation", "genius", "overcomplicating"] },
    { name: "Bhai bhai", description: "Two identical looking people pointing at each other saying bhai bhai. Used for two things that are unexpectedly the same, twins, copy paste situations in India.", image_url: "https://i.imgflip.com/2/4baxao.jpg", tags: ["same", "india", "copy", "identical", "bhai"] },
    { name: "Kejriwal confused", description: "A politician looking genuinely confused and questioning reality. Used for when something makes absolutely no sense, utter bewilderment, why is this happening.", image_url: "https://i.imgflip.com/7y2gzz.jpg", tags: ["confused", "politics", "india", "why", "bewildered"] },
    { name: "Chai wala", description: "The famous Pakistani chai wala or Indian chai vendor who became a model. Used for unexpected glow ups, hidden talent, beauty in unexpected places.", image_url: "https://i.imgflip.com/2/abiiky.jpg", tags: ["glow up", "unexpected", "india", "beauty", "viral"] },
    { name: "Dhinchak Pooja", description: "Dhinchak Pooja singing confidently despite questionable talent. Used for doing something confidently with zero self awareness, cringe but confident.", image_url: "https://i.imgflip.com/7y2gzz.jpg", tags: ["cringe", "confident", "india", "singing", "no self awareness"] },
    { name: "Jethalal shocked", description: "Jethalal from Taarak Mehta Ka Ooltah Chashmah with a shocked and panicked expression. Used for sudden shocking news, plans going wrong, Indian family drama situations.", image_url: "https://i.imgflip.com/2/470f65.jpg", tags: ["shocked", "panic", "india", "taarak mehta", "family"] },
    { name: "Babita ji smile", description: "Babita ji from Taarak Mehta smiling sweetly. Used for wholesome moments, innocent reactions, sweet situations.", image_url: "https://i.imgflip.com/7y2h00.jpg", tags: ["sweet", "wholesome", "india", "taarak mehta", "smile"] },
    { name: "Indian mom disappointed", description: "An Indian mother giving the classic disappointed look. Used for letting parents down, not becoming a doctor or engineer, disappointing family expectations.", image_url: "https://i.imgflip.com/7y2gzz.jpg", tags: ["disappointed", "india", "mom", "expectations", "family"] },
    { name: "Sharma ji ka beta", description: "Reference to the mythical Sharma ji's son who always scores 100 percent. Used for unrealistic parental comparisons, neighbour's perfect kid, impossible standards.", image_url: "https://i.imgflip.com/2/6wxb4e.jpg", tags: ["comparison", "india", "parents", "pressure", "sharma ji"] },
    { name: "IPL fan reaction", description: "An IPL cricket fan going absolutely crazy in the stands. Used for sports excitement, unexpected wins, losing your mind over a match.", image_url: "https://i.imgflip.com/7y2h00.jpg", tags: ["cricket", "ipl", "india", "fan", "excited"] },
    { name: "Rohit Sharma smile", description: "Rohit Sharma hitting a six and smiling casually like it was nothing. Used for doing something impressive without breaking a sweat, effortless excellence.", image_url: "https://i.imgflip.com/7y2h00.jpg", tags: ["cricket", "india", "effortless", "six", "rohit"] },
    { name: "RCB fan every year", description: "An RCB fan looking hopeful at the start of IPL season. Used for eternal optimism despite repeated failures, this year will be different, touching grass.", image_url: "https://i.imgflip.com/7y2gzz.jpg", tags: ["cricket", "rcb", "ipl", "hope", "losing"] },

    // ============ CARTOON MEMES ============
    { name: "Spongebob mocking", description: "SpongeBob SquarePants alternating between uppercase and lowercase letters mocking someone. Used for sarcastically repeating what someone said to mock them.", image_url: "https://i.imgflip.com/2/1p5q26.jpg", tags: ["mocking", "sarcasm", "spongebob", "cartoon", "repeat"] },
    { name: "Patrick Star dumb", description: "Patrick Star from SpongeBob saying something incredibly stupid with full confidence. Used for confidently wrong statements, stupid advice given seriously.", image_url: "https://i.imgflip.com/2/3132hg.jpg", tags: ["dumb", "stupid", "spongebob", "cartoon", "confident"] },
    { name: "Squidward window", description: "Squidward peeking through his window jealously at SpongeBob having fun. Used for jealousy, FOMO, watching others enjoy themselves while you suffer.", image_url: "https://i.imgflip.com/2/145qvv.jpg", tags: ["jealousy", "fomo", "spongebob", "cartoon", "watching"] },
    { name: "Tom chasing Jerry", description: "Tom the cat chasing Jerry the mouse endlessly. Used for endless pursuit, never catching something, persistent but failing chase.", image_url: "https://i.imgflip.com/2/4nma2x.jpg", tags: ["chase", "endless", "cartoon", "tom and jerry", "failure"] },
    { name: "Tom crying", description: "Tom the cat crying dramatically. Used for being overly dramatic about sadness, crying over small things, theatrical emotional reactions.", image_url: "https://i.imgflip.com/3pnhge.jpg", tags: ["crying", "dramatic", "cartoon", "tom and jerry", "sad"] },
    { name: "Jerry winning", description: "Jerry the mouse outsmarting Tom and winning. Used for the underdog winning, small person beating the big one, clever victory.", image_url: "https://i.imgflip.com/9vct.jpg", tags: ["winning", "underdog", "cartoon", "tom and jerry", "clever"] },
    { name: "Doraemon gadget", description: "Doraemon pulling out a magical gadget from his pocket to solve a problem. Used for having the perfect solution, pulling something out of nowhere, magical fix.", image_url: "https://i.imgflip.com/2/3fa51q.jpg", tags: ["solution", "gadget", "doraemon", "cartoon", "magic"] },
    { name: "Nobita crying", description: "Nobita from Doraemon crying and asking Doraemon for help. Used for being completely helpless, relying on others, lazy person needing rescue.", image_url: "https://i.imgflip.com/3pnhge.jpg", tags: ["helpless", "crying", "doraemon", "cartoon", "lazy"] },
    { name: "Shinchan mischief", description: "Shinchan doing something naughty with an innocent face. Used for causing trouble and acting innocent, pretending you didn't do anything wrong.", image_url: "https://i.imgflip.com/9vct.jpg", tags: ["naughty", "innocent", "shinchan", "cartoon", "mischief"] },
    { name: "Shinchan action kamen", description: "Shinchan posing as his superhero Action Kamen. Used for feeling like a superhero, dramatic posing, childhood fantasy moments.", image_url: "https://i.imgflip.com/26jxvz.jpg", tags: ["superhero", "pose", "shinchan", "cartoon", "childhood"] },
    { name: "Homer Simpson donut", description: "Homer Simpson drooling over a donut saying mmm donuts. Used for extreme food cravings, wanting something desperately, drooling over something desirable.", image_url: "https://i.imgflip.com/2/ixlim.jpg", tags: ["food", "craving", "simpsons", "cartoon", "desire"] },
    { name: "Homer Simpson bushes", description: "Homer Simpson slowly backing into a hedge to disappear from an awkward situation. Used for slowly backing out, avoiding confrontation, noping out gracefully.", image_url: "https://i.imgflip.com/2/2txtm1.jpg", tags: ["avoid", "escape", "simpsons", "cartoon", "awkward"] },
    { name: "Bart Simpson chalkboard", description: "Bart Simpson writing lines on a chalkboard as punishment. Used for being punished for the same mistake repeatedly, learning lessons the hard way.", image_url: "https://i.imgflip.com/2/106nxw.jpg", tags: ["punishment", "repeat", "simpsons", "cartoon", "mistake"] },
    { name: "Peter Griffin falling", description: "Peter Griffin from Family Guy falling and saying ow my leg repeatedly. Used for dramatic overreaction to minor pain, milking an injury.", image_url: "https://i.imgflip.com/2/60kh6p.jpg", tags: ["pain", "dramatic", "family guy", "cartoon", "overreaction"] },
    { name: "Bugs Bunny not my problem", description: "Bugs Bunny calmly walking away saying not my problem. Used for not caring about someone else's issues, walking away from drama, not my circus not my monkeys.", image_url: "https://i.imgflip.com/3lmzyx.jpg", tags: ["not my problem", "walking away", "bugs bunny", "cartoon", "unbothered"] },
    { name: "Scooby Doo mask reveal", description: "A Scooby Doo villain being unmasked to reveal who they really are. Used for revealing the true identity behind something, plot twist reveals, the real culprit.", image_url: "https://i.imgflip.com/2/2eeunw.jpg", tags: ["reveal", "identity", "scooby doo", "cartoon", "plot twist"] },
    { name: "Courage the cowardly dog", description: "Courage the dog looking absolutely terrified of everything. Used for extreme anxiety, being scared of normal things, paranoia, everything is terrifying.", image_url: "https://i.imgflip.com/2/4c1sgu.jpg", tags: ["scared", "anxiety", "courage", "cartoon", "terrified"] },
    { name: "Dexter laboratory secret", description: "Dexter hiding his secret laboratory from his family. Used for secret projects, hiding something important, having a hidden life.", image_url: "https://i.imgflip.com/26jxvz.jpg", tags: ["secret", "hidden", "dexter", "cartoon", "laboratory"] },
    { name: "Johnny Bravo mirror", description: "Johnny Bravo flexing and admiring himself in the mirror. Used for extreme narcissism, being obsessed with your own looks, self admiration.", image_url: "https://i.imgflip.com/2/vksti.jpg", tags: ["narcissism", "flex", "johnny bravo", "cartoon", "looks"] },
    { name: "Powerpuff Girls fight", description: "The Powerpuff Girls flying in to save the day. Used for girl power moments, team arriving to save the situation, heroes showing up.", image_url: "https://i.imgflip.com/2/arj8nv.jpg", tags: ["girl power", "team", "powerpuff", "cartoon", "save"] },
    { name: "Naruto run", description: "Naruto running with arms stretched back in the iconic ninja run pose. Used for running towards something important, anime style effort, going all out.", image_url: "https://i.imgflip.com/2/3b3ncx.jpg", tags: ["running", "naruto", "anime", "cartoon", "iconic"] },
    { name: "Vegeta it's over 9000", description: "Vegeta from Dragon Ball Z crushing his scouter and screaming it's over 9000. Used for something being unbelievably high or beyond expectations, off the charts.", image_url: "https://i.imgflip.com/2/3qgbb5.jpg", tags: ["over 9000", "dragonball", "anime", "cartoon", "extreme"] },
    { name: "Goku ultra instinct", description: "Goku achieving Ultra Instinct form with silver hair and glowing eyes. Used for unlocking maximum potential, going beyond your limits, final form achieved.", image_url: "https://i.imgflip.com/2/20h4or.jpg", tags: ["ultra instinct", "dragonball", "anime", "cartoon", "power"] },
    { name: "Pikachu I choose you", description: "Ash throwing a pokeball and choosing Pikachu. Used for making a bold choice, picking your favourite, I choose this option.", image_url: "https://i.imgflip.com/2/7j89ib.jpg", tags: ["choice", "pokemon", "anime", "cartoon", "pikachu"] },
    { name: "Tom and Jerry friendship", description: "Tom and Jerry moments when they unexpectedly become friends against a common enemy. Used for enemies teaming up, unlikely alliances, common enemy situations.", image_url: "https://i.imgflip.com/2za3u1.jpg", tags: ["friendship", "enemies", "tom and jerry", "cartoon", "alliance"] },

    // ============ SPORTS MEMES ============
    { name: "Cristiano Ronaldo SIUUU", description: "Cristiano Ronaldo doing his iconic SIUUU celebration jump and spin after scoring. Used for epic celebrations, winning moments, scoring a goal, achievement unlocked.", image_url: "https://i.imgflip.com/2/5r73ur.jpg", tags: ["celebration", "ronaldo", "football", "sports", "siuu"] },
    { name: "Messi sitting trophy", description: "Lionel Messi sitting on the pitch surrounded by trophies looking tired but victorious. Used for being exhausted after collecting all the wins, too many achievements.", image_url: "https://i.imgflip.com/7y2h00.jpg", tags: ["trophies", "messi", "football", "sports", "winning"] },
    { name: "Messi vs Ronaldo debate", description: "Two sides arguing passionately about Messi vs Ronaldo. Used for the greatest of all time debate, two camps that will never agree, endless argument.", image_url: "https://i.imgflip.com/345v97.jpg", tags: ["debate", "messi", "ronaldo", "football", "goat"] },
    { name: "Michael Jordan crying", description: "Michael Jordan crying at the podium during his Hall of Fame speech. Used for unexpected emotional breakdown, crying happy or sad tears, overwhelming emotions.", image_url: "https://i.imgflip.com/3pnhge.jpg", tags: ["crying", "jordan", "basketball", "sports", "emotional"] },
    { name: "LeBron James decision", description: "LeBron James making a dramatic decision to leave a team. Used for making a big dramatic exit, taking your talents elsewhere, leaving a situation dramatically.", image_url: "https://i.imgflip.com/2/1qssks.jpg", tags: ["decision", "lebron", "basketball", "sports", "leaving"] },
    { name: "Usain Bolt pointing", description: "Usain Bolt looking back at competitors while pointing at himself during a race he's clearly winning. Used for being so far ahead you can relax, winning effortlessly.", image_url: "https://i.imgflip.com/7y2h00.jpg", tags: ["winning", "bolt", "running", "sports", "effortless"] },
    { name: "Tiger Woods winning smile", description: "Tiger Woods pumping his fist with his iconic winning smile. Used for winning against all odds, comeback victory, dominant performance.", image_url: "https://i.imgflip.com/7y2h00.jpg", tags: ["winning", "tiger woods", "golf", "sports", "comeback"] },
    { name: "Federer crying winner", description: "Roger Federer crying after winning a Grand Slam tournament. Used for winning and still crying from emotion, overwhelming joy, tears of happiness.", image_url: "https://i.imgflip.com/3pnhge.jpg", tags: ["crying", "federer", "tennis", "sports", "emotional win"] },
    { name: "Penalty miss football", description: "A footballer missing a penalty kick and looking devastated. Used for failing at the most important moment, choking under pressure, so close yet so far.", image_url: "https://i.imgflip.com/1yxkcp.jpg", tags: ["miss", "penalty", "football", "sports", "failure"] },
    { name: "Red card football", description: "A football referee showing a red card to a player. Used for being kicked out, getting disqualified, someone who crossed the line and got punished.", image_url: "https://i.imgflip.com/2/6zz4r4.jpg", tags: ["red card", "football", "sports", "punishment", "out"] },
    { name: "Goalkeeper blunder", description: "A goalkeeper making a terrible mistake and letting in an easy goal. Used for making an embarrassing mistake in an important moment, epic fail at your job.", image_url: "https://i.imgflip.com/1ytdgt.jpg", tags: ["blunder", "goalkeeper", "football", "sports", "epic fail"] },
    { name: "NBA dunk reaction", description: "The crowd going absolutely crazy after a massive NBA slam dunk. Used for something so impressive it blows everyone's mind, crowd losing it.", image_url: "https://i.imgflip.com/3oevdk.jpg", tags: ["dunk", "nba", "basketball", "sports", "crowd reaction"] },
    { name: "Cricket bat raise", description: "A batsman raising his bat to the crowd after scoring a century. Used for celebrating a big milestone, acknowledging your achievement, century moment.", image_url: "https://i.imgflip.com/7y2h00.jpg", tags: ["century", "cricket", "sports", "milestone", "celebration"] },
    { name: "F1 podium champagne", description: "F1 drivers spraying champagne on the podium after a race. Used for celebrating a big win with style, victory party, we made it moments.", image_url: "https://i.imgflip.com/2/3fjbhk.jpg", tags: ["celebration", "f1", "formula1", "sports", "podium"] },
    { name: "Lewis Hamilton champion", description: "Lewis Hamilton celebrating a Formula 1 championship win. Used for dominating a competition, being the undisputed champion, record breaking wins.", image_url: "https://i.imgflip.com/7y2h00.jpg", tags: ["champion", "hamilton", "f1", "sports", "record"] },
    { name: "Neymar rolling", description: "Neymar rolling on the ground dramatically after minimal contact. Used for extreme exaggeration of pain, being a drama queen, overreacting to something minor.", image_url: "https://i.imgflip.com/1yxkcp.jpg", tags: ["dramatic", "neymar", "football", "sports", "overreacting"] },
    { name: "Mbappe speed", description: "Kylian Mbappe running at incredible speed leaving defenders behind. Used for being impossibly fast, leaving everyone in the dust, lightning speed.", image_url: "https://i.imgflip.com/1ur9b0.jpg", tags: ["speed", "mbappe", "football", "sports", "fast"] },
    { name: "Sports underdog wins", description: "An underdog team celebrating an unexpected victory against a much stronger opponent. Used for upsets, unexpected wins, David beats Goliath moments.", image_url: "https://i.imgflip.com/7y2h00.jpg", tags: ["underdog", "upset", "sports", "unexpected", "victory"] },
    { name: "Referee wrong decision", description: "A referee making an obviously wrong decision while players and fans react in disbelief. Used for terrible decisions, clear injustice, blind referee moments.", image_url: "https://i.imgflip.com/345v97.jpg", tags: ["referee", "wrong", "sports", "injustice", "disbelief"] },
    { name: "Extra time goal", description: "A player scoring a last minute goal in extra time to win the match. Used for winning at the very last second, clutch moments, never give up.", image_url: "https://i.imgflip.com/7y2h00.jpg", tags: ["last minute", "clutch", "sports", "football", "comeback"] },
    { name: "Sachin Tendulkar century", description: "Sachin Tendulkar raising his bat and looking to the sky after scoring a hundred. Used for legendary achievements, the god of cricket, milestone moments.", image_url: "https://i.imgflip.com/7y2h00.jpg", tags: ["century", "sachin", "cricket", "india", "legend"] },

    // ============ EXTRA POPULAR MEMES ============
    { name: "No no no yes", description: "A four panel meme rejecting multiple options then enthusiastically saying yes to the last one. Used for finally finding the right option after rejecting everything else.", image_url: "https://i.imgflip.com/2/30b1gx.jpg", tags: ["yes no", "choice", "finally", "preference"] },
    { name: "Types of headache", description: "A person with different things pressing on their head representing different types of stress. Used for multiple sources of stress, being squeezed from all sides.", image_url: "https://i.imgflip.com/2/1yz6z4.jpg", tags: ["stress", "headache", "pressure", "multiple problems"] },
    { name: "Nobody me at 3am", description: "Someone doing something weird or embarrassing alone at 3am. Used for late night activities, things you do when no one is watching, 3am energy.", image_url: "https://i.imgflip.com/2/9qx0va.jpg", tags: ["3am", "alone", "weird", "late night", "nobody"] },
    { name: "Brain during exam", description: "A brain completely shutting down during an important exam after functioning normally before. Used for blanking out under pressure, forgetting everything when it matters.", image_url: "https://i.imgflip.com/2/7i9jvv.jpg", tags: ["exam", "blank", "brain", "pressure", "forgetting"] },
    { name: "Student loan pain", description: "Someone being crushed under the weight of student loan debt. Used for financial burden, education costs, debt that follows you forever.", image_url: "https://i.imgflip.com/1yxkcp.jpg", tags: ["debt", "student loan", "financial", "burden", "education"] },
    { name: "Monday vs Friday", description: "A person looking dead on Monday and completely alive and happy on Friday. Used for the weekly struggle, dreading Mondays, living for weekends.", image_url: "https://i.imgflip.com/2/9utvx7.jpg", tags: ["monday", "friday", "work", "weekend", "energy"] },
    { name: "My sleep schedule", description: "A completely broken and chaotic sleep schedule graph. Used for terrible sleeping habits, staying up all night, destroyed sleep routine.", image_url: "https://i.imgflip.com/2/am8hl3.jpg", tags: ["sleep", "schedule", "night owl", "insomnia", "unhealthy"] },
    { name: "When the plan works", description: "Someone looking surprised and happy that their plan actually worked for once. Used for when something unexpectedly goes right, shocked at your own success.", image_url: "https://i.imgflip.com/2/3441g6.jpg", tags: ["plan", "success", "surprised", "works", "unexpected"] },
    { name: "Introvert at party", description: "An introvert sitting in the corner of a party waiting for it to end. Used for social anxiety, hating parties, wanting to go home, introvert energy.", image_url: "https://i.imgflip.com/2/5r10pj.jpg", tags: ["introvert", "party", "social anxiety", "corner", "home"] },
    { name: "Deadline approaching", description: "A person looking increasingly panicked as a deadline gets closer and closer. Used for procrastination consequences, running out of time, last minute panic.", image_url: "https://i.imgflip.com/2/6avrr2.jpg", tags: ["deadline", "panic", "procrastination", "time", "last minute"] },
// ============ MOVIES & SERIES ============
{ name: "Inception confused", description: "A person looking confused trying to understand the plot of Inception. Used for things that are too complicated to understand, mind bending situations, layers within layers.", image_url: "https://i.imgflip.com/26am.jpg", tags: ["confused", "movies", "complicated", "mind blown"] },
{ name: "Thanos perfectly balanced", description: "Thanos from Avengers saying perfectly balanced as all things should be. Used for when two things are exactly equal, fair outcomes, equilibrium situations.", image_url: "https://i.imgflip.com/2/303krn.jpg", tags: ["balanced", "thanos", "marvel", "movies", "fair"] },
{ name: "Spider-Man pointing", description: "Two Spider-Men pointing at each other confused about who is the real one. Used for two identical things, copy paste, can't tell the difference between two options.", image_url: "https://i.imgflip.com/2/1tkjq9.jpg", tags: ["same", "identical", "spiderman", "movies", "copy"] },
{ name: "Gandalf you shall not pass", description: "Gandalf from Lord of the Rings slamming his staff and saying you shall not pass. Used for blocking someone, refusing entry, hard no situations.", image_url: "https://i.imgflip.com/2/14xbe.jpg", tags: ["blocked", "refused", "gandalf", "lotr", "movies"] },
{ name: "Joker stairs dancing", description: "Joker dancing freely on the stairs feeling liberated. Used for not caring anymore, doing what you want, finally feeling free.", image_url: "https://i.imgflip.com/2/3broyk.jpg", tags: ["free", "joker", "movies", "dancing", "liberation"] },
{ name: "Tony Stark I am Iron Man", description: "Tony Stark snapping his fingers saying I am Iron Man. Used for mic drop moments, final power moves, ending an argument decisively.", image_url: "https://i.imgflip.com/46e43q.jpg", tags: ["power", "ironman", "marvel", "movies", "mic drop"] },
{ name: "Game of Thrones disappointing", description: "Game of Thrones fans reacting to the disappointing final season. Used for things that start great but end terribly, ruined expectations.", image_url: "https://i.imgflip.com/345v97.jpg", tags: ["disappointed", "got", "series", "ending", "betrayal"] },
{ name: "Breaking Bad I am the danger", description: "Walter White saying I am the one who knocks. Used for establishing dominance, being the real threat in the room.", image_url: "https://i.imgflip.com/2/rgttq.jpg", tags: ["danger", "breaking bad", "series", "power", "threat"] },
{ name: "The Office awkward silence", description: "Michael Scott from The Office staring into the camera during an extremely awkward moment. Used for uncomfortable silences, secondhand embarrassment.", image_url: "https://i.imgflip.com/2za3u1.jpg", tags: ["awkward", "the office", "series", "silence", "cringe"] },
{ name: "Friends how you doin", description: "Joey from Friends saying how you doin with a charming smile. Used for flirting, smooth approaches, trying your luck.", image_url: "https://i.imgflip.com/2/30aujs.jpg", tags: ["flirting", "friends", "series", "joey", "smooth"] },
{ name: "Stranger Things upside down", description: "The upside down from Stranger Things representing an alternate dark reality. Used for things going from normal to completely wrong.", image_url: "https://i.imgflip.com/2/34xq8t.jpg", tags: ["wrong", "stranger things", "series", "dark", "alternate"] },
{ name: "Squid Game red light green light", description: "Players frozen during red light green light in Squid Game. Used for suddenly having to stop what you're doing, freeze moments.", image_url: "https://i.imgflip.com/2/5p7xag.jpg", tags: ["stop", "squid game", "series", "freeze", "danger"] },
{ name: "Money Heist bella ciao", description: "The Professor from Money Heist with a master plan. Used for having an elaborate plan, being the mastermind, everything going according to plan.", image_url: "https://i.imgflip.com/26jxvz.jpg", tags: ["plan", "money heist", "series", "mastermind", "heist"] },
{ name: "Sherlock thinking", description: "Sherlock Holmes solving a complex problem with rapid deductions. Used for figuring something obvious out, overthinking a simple problem.", image_url: "https://i.imgflip.com/2/73u2t8.jpg", tags: ["thinking", "sherlock", "series", "deduction", "smart"] },
{ name: "Ted Lasso believe", description: "Ted Lasso pointing at the believe sign. Used for blind optimism, believing in yourself despite everything, underdog motivation.", image_url: "https://i.imgflip.com/2/66wogf.jpg", tags: ["believe", "ted lasso", "series", "optimism", "motivation"] },
{ name: "The Wire Omar coming", description: "Omar Little from The Wire walking the street fearlessly. Used for someone dangerous or impressive approaching, making an entrance.", image_url: "https://i.imgflip.com/2/3oi1la.jpg", tags: ["coming", "the wire", "series", "fearless", "entrance"] },
{ name: "Succession betrayal", description: "Characters from Succession backstabbing each other for power. Used for corporate betrayal, family drama, power hungry situations.", image_url: "https://i.imgflip.com/345v97.jpg", tags: ["betrayal", "succession", "series", "power", "corporate"] },
{ name: "Chernobyl not great not terrible", description: "Dyatlov from Chernobyl saying not great not terrible. Used for mediocre situations, things that are neither good nor bad, 3.6 roentgen.", image_url: "https://i.imgflip.com/2/33q0nv.jpg", tags: ["mediocre", "chernobyl", "series", "not great", "okay"] },

// ============ POLITICS ============
{ name: "Politicians shaking hands", description: "Two politicians shaking hands while hiding something behind their backs. Used for fake agreements, corrupt deals, smiling while lying.", image_url: "https://i.imgflip.com/2/9fonqt.jpg", tags: ["politics", "fake", "deal", "corrupt", "shaking hands"] },
{ name: "Election promises", description: "A politician making big promises before election versus after winning. Used for broken promises, saying one thing and doing another.", image_url: "https://i.imgflip.com/2/abbgag.jpg", tags: ["politics", "promises", "election", "lying", "before after"] },
{ name: "Government spending", description: "Government spending money on useless things while ignoring important issues. Used for misplaced priorities, wasting resources on wrong things.", image_url: "https://i.imgflip.com/60ck.jpg", tags: ["government", "spending", "priorities", "politics", "waste"] },
{ name: "Politician caught lying", description: "A politician caught in an obvious lie trying to explain it away. Used for getting caught, obvious lies, backtracking on statements.", image_url: "https://i.imgflip.com/1h7in3.jpg", tags: ["lying", "politics", "caught", "excuse", "backtrack"] },
{ name: "Tax money question", description: "A citizen asking where their tax money went with no answer. Used for government accountability, missing funds, where did money go.", image_url: "https://i.imgflip.com/1wjvgi.jpg", tags: ["tax", "money", "government", "accountability", "missing"] },
{ name: "Two parties same thing", description: "Two political parties that seem different but do the same things in power. Used for false choices, both sides being the same, illusion of choice.", image_url: "https://i.imgflip.com/2za3u1.jpg", tags: ["politics", "parties", "same", "choice", "illusion"] },
{ name: "Politician pointing blame", description: "A politician pointing at someone else to blame for their own failures. Used for deflecting blame, scapegoating, never taking responsibility.", image_url: "https://i.imgflip.com/9ehk.jpg", tags: ["blame", "politics", "deflect", "responsibility", "scapegoat"] },
{ name: "New leader same problems", description: "A new leader coming in promising change but everything stays the same. Used for false hope, disappointing leadership, plus ca change.", image_url: "https://i.imgflip.com/3qqrq0.jpg", tags: ["leader", "change", "politics", "same", "disappointment"] },

// ============ COLLEGE LIFE ============
{ name: "Assignment due tomorrow", description: "A student realising an assignment is due tomorrow and they haven't started. Used for last minute panic, procrastination consequences, all nighter incoming.", image_url: "https://i.imgflip.com/2/ar8bsj.jpg", tags: ["assignment", "college", "deadline", "panic", "procrastination"] },
{ name: "Attendance shortage", description: "A student checking their attendance percentage and seeing it's dangerously low. Used for attendance anxiety, skipping class consequences, detention fears.", image_url: "https://i.imgflip.com/1yxkcp.jpg", tags: ["attendance", "college", "shortage", "anxiety", "skipping"] },
{ name: "CGPA vs job requirements", description: "A student seeing a job requires 8.5 CGPA when they have 6.2. Used for gap between expectations and reality, qualification mismatch.", image_url: "https://i.imgflip.com/30b1gx.jpg", tags: ["cgpa", "college", "job", "requirements", "reality"] },
{ name: "Group project one person does everything", description: "One student doing the entire group project while others do nothing. Used for unequal work distribution, carrying the team, doing everything yourself.", image_url: "https://i.imgflip.com/1ytdgt.jpg", tags: ["group project", "college", "unfair", "carrying", "work"] },
{ name: "Professor marks attendance wrong", description: "A professor accidentally marking a student absent when they were present. Used for unfair treatment, clerical errors that affect you badly.", image_url: "https://i.imgflip.com/345v97.jpg", tags: ["attendance", "college", "professor", "unfair", "mistake"] },
{ name: "Exam next day studying memes", description: "A student who has an exam tomorrow but is scrolling memes instead of studying. Used for self destructive procrastination, can't stop scrolling.", image_url: "https://i.imgflip.com/3lmzyx.jpg", tags: ["exam", "college", "procrastination", "memes", "distraction"] },
{ name: "Copying assignment last minute", description: "Students frantically sharing assignments five minutes before submission. Used for last minute copying, borrowing work, submission panic.", image_url: "https://i.imgflip.com/3oevdk.jpg", tags: ["copying", "college", "assignment", "last minute", "sharing"] },
{ name: "Canteen food vs hostel mess", description: "Choosing between bad canteen food and worse hostel mess food. Used for choosing between two equally bad options, no good choices.", image_url: "https://i.imgflip.com/1yxkcp.jpg", tags: ["food", "college", "hostel", "canteen", "bad choices"] },
{ name: "Semester fees due", description: "A student getting the semester fee bill and looking at their empty bank account. Used for financial shock, unexpected large expenses.", image_url: "https://i.imgflip.com/3m13ew.jpg", tags: ["fees", "college", "money", "shock", "expensive"] },
{ name: "Backlog exam student", description: "A student who has to appear for backlog exams while friends move to next semester. Used for falling behind, having to repeat, embarrassing situation.", image_url: "https://i.imgflip.com/gk5el.jpg", tags: ["backlog", "college", "exam", "fail", "behind"] },
{ name: "First day vs last day college", description: "A student looking fresh and motivated on the first day of college versus exhausted and dead on the last day. Used for how college changes you.", image_url: "https://i.imgflip.com/1ur9b0.jpg", tags: ["college", "first day", "last day", "tired", "change"] },
{ name: "Placement season pressure", description: "A final year student panicking during campus placement season. Used for job hunting anxiety, being judged by companies, placement stress.", image_url: "https://i.imgflip.com/1yxkcp.jpg", tags: ["placement", "college", "job", "pressure", "anxiety"] },
{ name: "Professor asking who didn't submit", description: "A professor scanning the class asking who hasn't submitted the assignment while students look away. Used for avoiding eye contact, hiding from authority.", image_url: "https://i.imgflip.com/3lmzyx.jpg", tags: ["professor", "college", "assignment", "hiding", "avoiding"] },
{ name: "Night before exam energy", description: "A student going into hyper focus mode the night before an exam, reading the entire syllabus in one night. Used for last minute cramming, desperate studying.", image_url: "https://i.imgflip.com/1jwhww.jpg", tags: ["exam", "college", "night before", "cramming", "energy"] },

// ============ JOB & WORK ============
{ name: "Monday morning feeling", description: "A person looking absolutely dead inside on Monday morning before work. Used for dreading the work week, hating Mondays, existential work dread.", image_url: "https://i.imgflip.com/2/60l877.jpg", tags: ["monday", "work", "job", "morning", "dread"] },
{ name: "Boss says quick question", description: "A boss saying I have a quick question and it turning into a two hour meeting. Used for things that are never actually quick, meeting that should be emails.", image_url: "https://i.imgflip.com/1yxkcp.jpg", tags: ["boss", "work", "meeting", "quick", "job"] },
{ name: "Salary vs expenses", description: "A salary that looks decent versus the actual monthly expenses eating it all up. Used for money disappearing, not enough salary, cost of living.", image_url: "https://i.imgflip.com/2/6n1w3o.jpg", tags: ["salary", "job", "expenses", "money", "work"] },
{ name: "Work from home vs office", description: "Working from home in pyjamas versus having to dress up and commute to office. Used for WFH privilege, office return dread, hybrid work.", image_url: "https://i.imgflip.com/30b1gx.jpg", tags: ["wfh", "work", "office", "job", "commute"] },
{ name: "Appraisal time disappointment", description: "An employee expecting a big salary hike at appraisal and getting 3 percent. Used for disappointing raises, appraisal betrayal, underpaid workers.", image_url: "https://i.imgflip.com/3oevdk.jpg", tags: ["appraisal", "salary", "job", "disappointment", "hike"] },
{ name: "Fresher job requirements", description: "A fresher job listing requiring 5 years of experience for an entry level role. Used for impossible job requirements, entry level that isn't entry level.", image_url: "https://i.imgflip.com/1o00in.jpg", tags: ["fresher", "job", "experience", "requirements", "impossible"] },
{ name: "Reply all email disaster", description: "Someone accidentally hitting reply all on a company-wide email. Used for public mistakes, accidental exposure, email disasters.", image_url: "https://i.imgflip.com/3oevdk.jpg", tags: ["email", "work", "mistake", "reply all", "disaster"] },
{ name: "Office gossip meeting", description: "Colleagues gathering to gossip about something that happened in the office. Used for workplace drama, office politics, gossip spreading.", image_url: "https://i.imgflip.com/345v97.jpg", tags: ["gossip", "office", "work", "drama", "colleagues"] },
{ name: "Overtime unpaid", description: "An employee working late unpaid overtime while boss goes home early. Used for exploitation, unpaid work, unfair treatment at job.", image_url: "https://i.imgflip.com/1ytdgt.jpg", tags: ["overtime", "work", "unpaid", "job", "exploitation"] },
{ name: "Job interview went well", description: "A candidate thinking an interview went great and then never hearing back. Used for false confidence, ghosting after interviews, job rejection.", image_url: "https://i.imgflip.com/26jxvz.jpg", tags: ["interview", "job", "ghosted", "rejection", "confident"] },
{ name: "Toxic coworker", description: "A coworker who makes everyone's life difficult while somehow never getting in trouble. Used for workplace toxicity, untouchable bad employees.", image_url: "https://i.imgflip.com/9vct.jpg", tags: ["toxic", "coworker", "work", "job", "difficult"] },
{ name: "Team meeting that could be email", description: "A pointless meeting that could have been a two line email. Used for unnecessary meetings, wasted time, pointless gatherings.", image_url: "https://i.imgflip.com/2fm6x.jpg", tags: ["meeting", "email", "work", "pointless", "time waste"] },
{ name: "LinkedIn humble brag", description: "A person posting a humble brag on LinkedIn about their amazing achievement. Used for fake modesty, social media showing off, LinkedIn culture.", image_url: "https://i.imgflip.com/4t0m5.jpg", tags: ["linkedin", "humble brag", "job", "social media", "showing off"] },
{ name: "Resignation letter fantasy", description: "An employee fantasising about writing a dramatic resignation letter. Used for wanting to quit, fantasy of leaving a bad job, dream resignation.", image_url: "https://i.imgflip.com/3lmzyx.jpg", tags: ["resign", "quit", "job", "fantasy", "leaving"] },

// ============ TRAVEL ============
{ name: "Budget vs actual travel cost", description: "A traveller planning a cheap trip and the actual cost being triple the budget. Used for travel expenses going out of control, underestimating costs.", image_url: "https://i.imgflip.com/3m13ew.jpg", tags: ["travel", "budget", "expensive", "cost", "planning"] },
{ name: "Airport security check", description: "A traveller going through airport security and setting off the alarm despite having nothing. Used for random inconvenience, being stopped for no reason.", image_url: "https://i.imgflip.com/2/a3ycpw.jpg", tags: ["airport", "travel", "security", "alarm", "inconvenience"] },
{ name: "Flight delayed", description: "An airport departure board showing all flights delayed. Used for travel plans falling apart, waiting at airports, delay frustration.", image_url: "https://i.imgflip.com/2/6h4j8g.jpg", tags: ["flight", "delayed", "travel", "airport", "waiting"] },
{ name: "Hotel room expectation vs reality", description: "A hotel room that looked amazing on the booking website versus the depressing reality on arrival. Used for false advertising, disappointment on arrival.", image_url: "https://i.imgflip.com/30b1gx.jpg", tags: ["hotel", "travel", "expectation", "reality", "disappointment"] },
{ name: "Tourist trap prices", description: "A tourist being charged an insane amount for basic food near a famous landmark. Used for tourist trap pricing, being overcharged for location.", image_url: "https://i.imgflip.com/60ck.jpg", tags: ["tourist", "travel", "expensive", "trap", "overpriced"] },
{ name: "Lost in foreign country", description: "A tourist completely lost in a foreign country with no signal and a dead phone. Used for being completely helpless abroad, travel disasters.", image_url: "https://i.imgflip.com/1wjvgi.jpg", tags: ["lost", "travel", "foreign", "no signal", "helpless"] },
{ name: "Passport expiry panic", description: "A traveller discovering their passport has expired one day before an international trip. Used for last minute document disasters, travel panic.", image_url: "https://i.imgflip.com/3qqrq0.jpg", tags: ["passport", "travel", "expired", "panic", "disaster"] },
{ name: "Overpacking luggage", description: "A traveller trying to close an overpacked suitcase that won't shut. Used for bringing too much, overpacking, can't travel light.", image_url: "https://i.imgflip.com/1ytdgt.jpg", tags: ["packing", "travel", "luggage", "overpack", "suitcase"] },
{ name: "Travel Instagram vs reality", description: "A stunning travel photo on Instagram versus the crowded tourist reality behind the camera. Used for social media fakery, staged travel content.", image_url: "https://i.imgflip.com/30b1gx.jpg", tags: ["instagram", "travel", "reality", "fake", "tourist"] },
{ name: "Middle seat on flight", description: "A passenger stuck in the middle seat between two large passengers on a long flight. Used for being uncomfortable, bad luck situations, worst position.", image_url: "https://i.imgflip.com/1yxkcp.jpg", tags: ["flight", "middle seat", "travel", "uncomfortable", "bad luck"] },
{ name: "Train missed by seconds", description: "A person running to catch a train and watching the doors close right in front of them. Used for missing something by a tiny margin, so close yet so far.", image_url: "https://i.imgflip.com/3oevdk.jpg", tags: ["train", "travel", "missed", "seconds", "close"] },
{ name: "Travel plan vs actual trip", description: "An elaborate travel itinerary versus sleeping in the hotel all day because you're exhausted. Used for ambitious plans that fall apart on execution.", image_url: "https://i.imgflip.com/26jxvz.jpg", tags: ["travel", "plan", "itinerary", "reality", "exhausted"] }
]


// async function seed() {
//     const client = await pool.connect()
//     try {
//         console.log('Seeding memes...')
//         for (const meme of memes) {
//             await client.query(
//                 `INSERT INTO memes (name, description, image_url, tags)
//             VALUES($1, $2, $3, $4)
//             ON CONFLICT DO NOTHING`,
//                 [meme.name, meme.description, meme.image_url, meme.tags]
//             )
//             console.log(`✓ ${meme.name}`)
//         }
//         console.log(`\nDone! Seeded ${memes.length} memes.`)
//     } finally {
//         client.release()
//         process.exit(0)

//     }
//     seed().catch(err => {
//         console.error(err)
//         process.exit(1)
//     })

// }

console.log('Script started')

async function seed() {
    console.log('Connecting to DB...')
    const client = await pool.connect()
    console.log('Connected!')
    try {
        console.log('Seeding memes...')
        for (const meme of memes) {
            await client.query(
                `INSERT INTO memes (name, description, image_url, tags)
         VALUES ($1, $2, $3, $4)
         ON CONFLICT DO NOTHING`,
                [meme.name, meme.description, meme.image_url, meme.tags]
            )
            console.log(`✓ ${meme.name}`)
        }
        console.log(`\nDone! Seeded ${memes.length} memes.`)
    } catch (err) {
        console.error('Error:', err.message)
    } finally {
        client.release()
        process.exit(0)
    }
}

seed().catch(err => {
    console.error('Outer error:', err.message)
    process.exit(1)
})